# Generated by Django 5.2.13 on 2026-08-07 23:29

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='telefone')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['username'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('bairro', models.CharField(max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='estado')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('referencia', models.CharField(blank=True, max_length=150, verbose_name='referência')),
                ('principal', models.BooleanField(default=False, verbose_name='principal')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='usuarios.usuario', verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'endereço de usuário',
                'verbose_name_plural': 'endereços de usuários',
                'ordering': ['usuario__username', '-principal', 'logradouro'],
            },
        ),
    ]
