# Generated by Django 5.2.13 on 2026-08-07 23:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'categoria de estoque',
                'verbose_name_plural': 'categorias de estoque',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('PCT', 'Pacote'), ('CX', 'Caixa')], default='UN', max_length=3, verbose_name='unidade de medida')),
                ('quantidade_atual', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='quantidade atual')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='estoque mínimo')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='preço de custo')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='data de validade')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='estoque.categoriaestoque', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'item do estoque',
                'verbose_name_plural': 'itens do estoque',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('PERDA', 'Perda'), ('AJUSTE', 'Ajuste')], max_length=10, verbose_name='tipo')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='motivo')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.itemestoque', verbose_name='item')),
            ],
            options={
                'verbose_name': 'movimentação de estoque',
                'verbose_name_plural': 'movimentações de estoque',
                'ordering': ['-criada_em'],
            },
        ),
    ]
