# Generated by Django 5.2.13 on 2026-09-27 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_endereco_entrega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega_texto',
            field=models.CharField(blank=True, max_length=500, verbose_name='endereço de entrega no pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estoque_baixado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='estoque baixado em'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='origem',
            field=models.CharField(choices=[('SITE', 'Site'), ('BALCAO', 'Balcão')], default='BALCAO', max_length=10, verbose_name='origem'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='registrado por'),
        ),
    ]
