# Generated by Django 5.2.13 on 2026-09-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_endereco_entrega_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='checkout_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco_entrega_texto',
            field=models.TextField(blank=True, verbose_name='endereço de entrega no pedido'),
        ),
    ]
