# Generated by Django 5.2.13 on 2026-09-27 17:59

from django.db import migrations, models


def preencher_conclusoes_anteriores(apps, schema_editor):
    Pedido = apps.get_model('pedidos', 'Pedido')
    Pedido.objects.using(schema_editor.connection.alias).filter(
        status='ENTREGUE', concluido_em__isnull=True,
    ).update(concluido_em=models.F('atualizado_em'))


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_checkout_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='concluido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(preencher_conclusoes_anteriores, migrations.RunPython.noop),
    ]
