# Generated by Django 6.0.7 on 2026-08-15 02:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'categoria de pizza',
                'verbose_name_plural': 'categorias de pizza',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='pizzas/', verbose_name='imagem')),
                ('disponivel', models.BooleanField(default=True, verbose_name='disponível')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pizzas', to='cardapio.categoriapizza', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'pizza',
                'verbose_name_plural': 'pizzas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ReceitaPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade utilizada')),
                ('item_estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='estoque.itemestoque', verbose_name='item do estoque')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receita', to='cardapio.pizza', verbose_name='pizza')),
            ],
            options={
                'verbose_name': 'receita da pizza',
                'verbose_name_plural': 'receitas das pizzas',
                'ordering': ['pizza__nome', 'item_estoque__nome'],
            },
        ),
        migrations.AddField(
            model_name='pizza',
            name='itens_estoque',
            field=models.ManyToManyField(related_name='pizzas', through='cardapio.ReceitaPizza', to='estoque.itemestoque', verbose_name='itens do estoque'),
        ),
        migrations.AddConstraint(
            model_name='receitapizza',
            constraint=models.UniqueConstraint(fields=('pizza', 'item_estoque'), name='item_estoque_unico_por_pizza'),
        ),
    ]
