# Generated by Django 5.2.13 on 2026-07-28 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitapizza',
            name='item_estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='estoque.itemestoque', verbose_name='item do estoque'),
        ),
        migrations.AddField(
            model_name='receitapizza',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receita', to='cardapio.pizza', verbose_name='pizza'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='itens_estoque',
            field=models.ManyToManyField(related_name='pizzas', through='cardapio.ReceitaPizza', to='estoque.itemestoque', verbose_name='itens do estoque'),
        ),
        migrations.AddConstraint(
            model_name='receitapizza',
            constraint=models.UniqueConstraint(fields=('pizza', 'item_estoque'), name='item_estoque_unico_por_pizza'),
        ),
    ]
